version: '3.7'

volumes:
    grafana_data: {}

networks:
  front-tier:
  back-tier:

services:
  postgres:
    container_name: postgres
    image: postgres
    restart: always
    environment: 
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    networks:
      - back-tier

  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    restart: always
    environment:
      - GF_INSTALL_PLUGINS=natel-plotly-panel
    volumes:
      - ./config/grafana_datasources.yaml:/etc/grafana/provisioning/datasources/datasource.yaml:ro
      - ./config/grafana_dashboards.yaml:/etc/grafana/provisioning/dashboards/dashboards.yaml:ro
      - ./src/dashboards:/opt/grafana/dashboards
      - grafana_data:/var/lib/grafana
    networks:
      - back-tier
      - front-tier
