{
 "title": "Evidently Data Drift Dashboard - Advanced",
 "time": { "from": "2012-02-17T12:46:27.925Z", "to": "2033-02-26T12:46:28.181Z" },
 "templating": {
  "list": [
   {
    "name": "Feature",
    "query": "SELECT DISTINCT \"Feature\" from drift_table;"
   },
   {
    "name": "Date",
    "query": "SELECT DISTINCT to_char(\"Datetime\",'yyyy-MM-DD') AS \"Datetime\" from drift_table;"
   }
  ]
 },
 "panels": [
  {
   "title": "Reference Distribution",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  \"Datetime\" AS \"time\",\n  avg(y) AS \"y\",\n  x AS \"x\"\nFROM distribution\nWHERE\n  \"Feature\" = '$Feature' AND\n  \"Datetime\" = '$Date' AND\n  \"Distribution Type\" = 'Reference Distribution'\nGROUP BY \"Feature\", x, \"Datetime\"\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Current Distribution",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  \"Datetime\" AS \"time\",\n  avg(y) AS \"y\",\n  x AS \"x\"\nFROM distribution\nWHERE\n  \"Feature\" = '$Feature' AND\n  \"Datetime\" = '$Date' AND\n  \"Distribution Type\" = 'Current Distribution'\nGROUP BY \"Feature\", x, \"Datetime\"\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Data Drift",
   "type": "natel-plotly-panel",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT\n  \"x\",\n  avg(y1) AS \"y1\",\n  avg(y2) AS \"y2\",\n  avg(y3) AS \"y3\"\nFROM drift_chart\nWHERE\n  \"Feature\" = '$Feature' AND \"Datetime\" = '$Date'\nGROUP BY \"x\""
    }
   ]
  },
  {
   "title": "Data Distribution",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "rawSql": "SELECT\n  x\nFROM data_distr\nWHERE\n  \"Feature\" = '$Feature' AND\n  \"Datetime\" = '$Date' AND \"Type\" = 'Current'"
    },
    {
     "rawSql": "SELECT\n  x\nFROM data_distr\nWHERE\n  \"Feature\" = '$Feature' AND\n  \"Datetime\" = '$Date' AND \"Type\" = 'Reference'"
    }
   ]
  }
 ]
}