{
 "title": "Evidently Data Drift Dashboard",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  { "title": "General Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Dataset Drift",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT\n\"Datetime\",\nMAX(CASE \"Data Drift\" WHEN 'Not Detected' THEN 0 ELSE 1 END) AS \"data drift\"\nFROM drift_table\nGROUP BY \"Datetime\"\nORDER BY \"Datetime\" ASC;"
    }
   ]
  },
  {
   "title": "Share of drifted features",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "SELECT\n\"Datetime\" as \"time\", \n       (SUM(CASE \"Data Drift\" WHEN 'Not Detected' THEN 0 ELSE 1 END)/COUNT(\"Feature\")::decimal)*100 AS share\nFROM drift_table\nGROUP BY \"Datetime\""
    }
   ]
  },
  {
   "title": "# of drifted features",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  count(DISTINCT \"Feature\") AS \"Feature\"\nFROM drift_table\nWHERE\n  $__timeFilter(\"Datetime\") AND\n  \"Data Drift\" = 'Detected'"
    }
   ]
  },
  {
   "title": "# of features",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  count(DISTINCT \"Feature\") AS \"Feature\"\nFROM drift_table\nWHERE\n  $__timeFilter(\"Datetime\")"
    }
   ]
  },
  { "title": "Detailed Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "P-value of features",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "rawSql": "SELECT\n  \"Datetime\" AS \"time\",\n  \"Feature\" AS metric,\n  \"Drift Score\"\nFROM drift_table\nWHERE\n  $__timeFilter(\"Datetime\")\nORDER BY 1,2"
    }
   ]
  }
 ]
}